### ISSUE TITLE
doesn't know powerdns-release-service-db

### ISSUE THREAD

**Issue by lillianphyoe** [aescanero/helm-charts#14]
I applied with helm.
helm install powerdns-release -f values.yaml aecharts/powerdns 
and I got this error. 
![image](https://user-images.githubusercontent.com/19262583/93556492-dd3af900-f99e-11ea-9d8c-9e180bc9326e.png)

I can access database service ip through worker node. Someone please help me?

**Comment by aescanero** [comment]
Update to version 0.1.9 to make value powerdns.mysql_host valid again

**Comment by lillianphyoe** [comment]
Thank you so much sir! it may be my core dns error. let me update after I get it. 
![image](https://user-images.githubusercontent.com/19262583/93665175-68e58000-fa9a-11ea-900c-18f7817c7bec.png)
