### ISSUE TITLE
what did i miss?

### ISSUE THREAD

**Issue by outbackdingo** [aescanero/helm-charts#2]
helm install powerdns \                                                                19:56  27.02.20  56.14G RAM 
  --set domain=domain.com \
https://raw.githubusercontent.com/aescanero/helm-powerdns/master/test/powerdns.tgz
Error: failed to download "https://raw.githubusercontent.com/aescanero/helm-powerdns/master/test/powerdns.tgz" (hint: running `helm repo update` may help)

**Comment by aescanero** [comment]
Please check with:

helm repo add aecharts https://raw.githubusercontent.com/aescanero/helm-charts/master/
helm repo update
helm install --set domain=domain.com aecharts/powerdns

**Comment by aescanero** [comment]
Chart update to 0.1.7, tested in EKS
