### ISSUE TITLE
unable to run on ARM64 based k3s

### ISSUE THREAD

**Issue by ebkde** [aescanero/helm-charts#8]
Hi,

I tried to set up powerdns on my (ARM64 based) k3s Cluster, following https://www.disasterproject.com/powerdns-overkubernetes-helm-v3/
When I run `helm install pdns aecharts/powerdns` all seems to run well but all containers except the mariadb one in that pod keep crashing. When I try to take a look at the logs (`kubectl logs -p podname containername`) I only get the following:
`standard_init_linux.go:211: exec user process caused "exec format error"`

Could this be due to my cluster running on Arm64?

As I'm fairly new to this, any help on this would be highly appreciated

**Comment by ebkde** [comment]
Hi,

I was able to solve that by myself. The Arm64 Architecture was the cause of that problem. I solved it by rebuilding the pdns-mysql and docker-powerdns-admin-alpine images in docker on my cluster. These images are available on docker hub via ebkde/pdns-mysql-arm64 and ebkde/docker-powerdns-admin-alpine-arm64.

@aescanero: Since your Helm Chart is very flexible (thank you for that) running `helm install pdns --set powerdns.image.repository=ebkde/pdns-mysql-arm64 --set powerdnsadmin.image.repository=ebkde/docker-powerdns-admin-alpine-arm64 aecharts/powerdns` just works out of the box.
I'm not sure if this approach is the best one or if it would make more sense to add these images to your already existing dockerhub repositories (like mariadb which provides imaged for different architectures). If the latter would be better please advise on how to do this.

Many thanks 
ebkde

**Comment by aescanero** [comment]
Actually, I don't have a helm (and dockerfiles) valid for ARM, this is because I need a new rasp (actually I have a old and broken one). I'll get one to test powerdns over ARM at December
